# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: yarn && cd bot && yarn && npm i -g nodemon # runs during prebuild
    command: yarn rw dev
    command: cd bot && cp .template.env .env && nodemon -e yarn start


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8910
    onOpen: open-preview
